

#Taller 1 DEEP LEARNIG
Juan Nicolás Romero Estupiñan
#
Objetivo: comprender el funcionamiento de un perceptron


In [3]:
#Importamos librerias necesarias
import numpy as np

#Creamos nuestra matriz
X=np.array([[0.84, 0.35, 0.78],
            [0.12, 0.24, 0.66],
            [0.74, 0.97, 0.19],
            [0.52, 0.31, 0.83]])

#Matriz y su forma impresos
print(X)
print("Forma de x", X.shape)

[[0.84 0.35 0.78]
 [0.12 0.24 0.66]
 [0.74 0.97 0.19]
 [0.52 0.31 0.83]]
Forma de x (4, 3)


In [6]:
#Establecemos pesos y bias
W= np.array([0.4, 0.2, 0.3])
bias= -0.4

#Datos impresos
print("Pesos: ", W)
print("Bias:", bias)

Pesos [0.4 0.2 0.3]
Bias: -0.4


In [9]:
#Calculo de la matriz
Z= X @ W + bias

#Resultado impreso
print("Resultado antes de decidir: ")
print(Z)

Resultado antes de decidir: 
[ 0.24  -0.106  0.147  0.119]


In [10]:
# Función de activación escalón
# Si el valor es mayor o igual a 0 devuelve 1,
# de lo contrario devuelve 0.
def funcion_escalon(z):
    return np.where(z >= 0, 1, 0)

# Aplicamos la función a todos los resultados
prediccion = funcion_escalon(Z)

print("Predicciones:")
print(prediccion)

Predicciones:
[1 0 1 1]


In [15]:
# Función sigmoide

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Establecemos nuevos pesos y bias

W1 = np.array([[0.7],
               [0.1],
               [0.2]])

bias1 = 0.4

# Calculamos la salida de la neurona

Z1 = X @ W1 + bias1

# Aplicamos función de activación

A1 = sigmoid(Z1)

# Resultado impreso

print("Salida de la red neuronal de una capa:")
print(A1)

Salida de la red neuronal de una capa:
[[0.76476795]
 [0.65475346]
 [0.74135057]
 [0.72332198]]


In [16]:
# Pesos entrada -> capa oculta

W1 = np.array([[0.7, 0.1],
               [0.1, 0.5],
               [0.2, 0.6]])

bias1 = np.array([0.1, 0.1])

# Cálculo capa oculta

Z1 = X @ W1 + bias1

A1 = sigmoid(Z1)

print("Salida capa oculta:")
print(A1)

Salida capa oculta:
[[0.70661495 0.69572022]
 [0.58419052 0.65203583]
 [0.67983203 0.6841695 ]
 [0.65948499 0.69104301]]


In [18]:
# Pesos capa oculta -> salida

W2 = np.array([[0.7],
               [0.8]])

bias2 = 0.2

# Cálculo capa de salida

Z2 = A1 @ W2 + bias2

A2 = sigmoid(Z2)

print("Salida final de la red multicapa:")
print(A2)

prediccion_final = np.where(A2 >= 0.5, 1, 0)
print("Prediccion final:")
print(prediccion_final)

Salida final de la red multicapa:
[[0.77750867]
 [0.7559426 ]
 [0.77262937]
 [0.7710896 ]]
Prediccion final:
[[1]
 [1]
 [1]
 [1]]


Conclusiones

1. Se implementó un perceptrón utilizando operaciones matriciales con NumPy.
2. Se desarrolló una red neuronal de una capa utilizando la función sigmoide.
3. Se implementó una red neuronal multicapa agregando una capa oculta.
4. NumPy permitió realizar los cálculos de forma vectorizada y eficiente.
5. Se comprendió el proceso de cálculo de pesos, bias y funciones de activación.